In [127]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn import tree
import warnings

In [ ]:
df_crop = pd.read_csv('/home/noturminesv/projects/gis-ml/dataset/dataset_yogyakarta_augmented.csv')

In [129]:
df_crop.head()

,temperature,humidity,rainfall,ph,nitrogen,phosphorous,potassium,carbon,soil,label
0,22.600000,73.200000,246.300000,6.470000,67.53,42.8400,76.0100,3.66,Loamy Soil,chives
1,31.300000,67.300000,107.800000,6.380000,23.90,63.3100,88.8700,1.62,Sandy Loam,peanut
2,29.572403,93.618703,27.569186,6.559763,54.24,93.8000,48.3500,1.14,Loamy Soil,muskmelon
3,16.188204,90.728507,108.583437,7.755478,56.81,59.7865,55.1455,1.21,Peaty Soil,orange
4,24.288889,83.036879,54.765762,6.653868,56.13,101.9700,61.1000,0.65,Neutral Soil,watermelon

In [130]:
df_crop.tail()

,temperature,humidity,rainfall,ph,nitrogen,phosphorous,potassium,carbon,soil,label
6286,25.965342,89.637252,58.993108,6.849472,57.6525,147.812772,92.6700,1.48,Loamy Soil,watermelon
6287,28.939399,81.439718,106.717373,6.664819,29.5400,37.890000,49.3100,2.23,Loamy Soil,mungbean
6288,24.073460,60.732411,110.870027,6.879552,33.0000,36.000000,32.0000,845.00,Loamy Soil,sweetpotato
6289,32.136814,78.930776,139.809395,6.561807,25.9500,34.440000,62.3100,1.97,Sandy Loam,mungbean
6290,22.504573,61.891003,245.878798,4.903373,69.0300,38.860000,55.4215,2.22,Acidic Soil,tea

In [131]:
df_crop.shape

(6291, 10)

In [132]:
df_crop.columns

Index(['temperature', 'humidity', 'rainfall', 'ph', 'nitrogen', 'phosphorous',
       'potassium', 'carbon', 'soil', 'label'],
      dtype='object')

In [133]:
df_crop['label'].unique()

array(['chives', 'peanut', 'muskmelon', 'orange', 'watermelon', 'coffee',
       'banana', 'garlic', 'cabbage', 'sweetpotato', 'tea', 'mango',
       'soybean', 'rice', 'papaya', 'shallots', 'maize', 'mungbean',
       'cassava', 'chilli'], dtype=object)

In [134]:
crop_mapping = {
    # Pertanian
    'rice': 'Padi',
    'maize': 'Jagung',
    'soybean': 'Kacang Kedelai',
    'mungbean': 'Kacang Hijau',
    'peanut': 'Kacang Tanah',
    'sweetpotato': 'Ubi Jalar',
    'cassava': 'Singkong',
    # Hortikultura
    'mango': 'Mangga',
    'orange': 'Jeruk',
    'papaya': 'Pepaya',
    'banana': 'Pisang',
    'shallots': 'Bawang Merah',
    'garlic': 'Bawang Putih',
    'chilli': 'Cabai',
    'chives': 'Daun Bawang',
    'cabbage': 'Kubis',
    'watermelon': 'Semangka',
    'muskmelon': 'Melon',
    # Perkebunan
    'tea': 'Teh',
    'coffee': 'Kopi',
}
df_crop['label'] = df_crop['label'].replace(crop_mapping)

In [135]:
df_crop.dtypes

temperature    float64
humidity       float64
rainfall       float64
ph             float64
nitrogen       float64
phosphorous    float64
potassium      float64
carbon         float64
soil            object
label           object
dtype: object

In [136]:
# sns.heatmap(df_crop.corr(),annot=True)

In [137]:
features = ['temperature', 'humidity', 'rainfall']
X = df_crop[features]

y = df_crop['label']

In [138]:
acc = []
model = []

In [139]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [140]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score

NaiveBayes = GaussianNB()

NaiveBayes.fit(X_train,y_train)

predicted_values = NaiveBayes.predict(X_test)
x = metrics.accuracy_score(y_test, predicted_values)
acc.append(x)
model.append('Naive Bayes')

print(classification_report(y_test,predicted_values))

                precision    recall  f1-score   support

  Bawang Merah       0.71      0.57      0.63        60
  Bawang Putih       0.42      0.48      0.45        60
         Cabai       0.31      0.27      0.29        60
   Daun Bawang       0.56      0.47      0.51        60
        Jagung       0.85      0.67      0.75        60
         Jeruk       0.95      0.97      0.96        60
  Kacang Hijau       0.64      0.55      0.59       120
Kacang Kedelai       0.42      0.42      0.42        60
  Kacang Tanah       0.53      0.73      0.62        60
          Kopi       0.73      0.62      0.67        60
         Kubis       0.48      0.48      0.48        60
        Mangga       1.00      1.00      1.00        60
         Melon       1.00      1.00      1.00        60
          Padi       0.75      0.80      0.77        60
        Pepaya       0.96      0.83      0.89        60
        Pisang       0.69      0.78      0.73        60
      Semangka       0.86      1.00      0.92        60
      Singkong       0.64      0.87      0.74        53
           Teh       0.78      0.70      0.74        60
     Ubi Jalar       0.87      0.98      0.92        66

      accuracy                           0.70      1259
     macro avg       0.71      0.71      0.70      1259
  weighted avg       0.70      0.70      0.70      1259

In [141]:
scores = cross_val_score(NaiveBayes, X, y, cv=5) 

print("--- Hasil Cross-Validation ---")
print("Akurasi untuk setiap fold:", scores)
print("Rata-rata Akurasi:", scores.mean())
print("Standar Deviasi Akurasi:", scores.std())

--- Hasil Cross-Validation ---
Akurasi untuk setiap fold: [0.71247021 0.71224165 0.68759936 0.71303657 0.69952305]
Rata-rata Akurasi: 0.7049741700771931
Standar Deviasi Akurasi: 0.01005592154022024

In [ ]:
import pickle
Model_pkl_filename = '/home/noturminesv/projects/gis-ml/model/ModelClassifier.pkl'
Model_pkl = open(Model_pkl_filename, 'wb')
pickle.dump(NaiveBayes, Model_pkl)
Model_pkl.close()

In [143]:
data = df_crop
data['label'].unique()

data['min_range_temperature'] = 0
data['max_range_temperature'] = 0
data['min_range_humidity'] = 0
data['max_range_humidity'] = 0
data['min_range_rainfall'] = 0
data['max_range_rainfall'] = 0

for i in data['label'].unique():
    data.loc[data['label'] == i, 'min_range_temperature'] = data[data['label'] == i]['temperature'].min()
    data.loc[data['label'] == i, 'max_range_temperature'] = data[data['label'] == i]['temperature'].max()
    data.loc[data['label'] == i, 'min_range_humidity'] = data[data['label'] == i]['humidity'].min()
    data.loc[data['label'] == i, 'max_range_humidity'] = data[data['label'] == i]['humidity'].max()
    data.loc[data['label'] == i, 'min_range_rainfall'] = data[data['label'] == i]['rainfall'].min()
    data.loc[data['label'] == i, 'max_range_rainfall'] = data[data['label'] == i]['rainfall'].max()
    
data = data.drop_duplicates(subset='label')

data = data[['label', 'min_range_temperature', 'max_range_temperature', 'min_range_humidity', 'max_range_humidity', 'min_range_rainfall', 'max_range_rainfall']]

In [144]:
harvest_time_map = {
    'Padi': 115,
    'Jagung': 90,
    'Semangka': 70,
    'Melon': 75,
    'Pepaya': 210,
    'Mangga': 125,
    'Teh': 120,
    'Pisang': 90,
    'Jeruk': 180,
    'Kopi': 270,
    'Ubi Jalar': 90,
    'Singkong': 120,
    'Kacang Kedelai': 90,
    'Kacang Hijau': 60,
    'Kacang Tanah': 90,
    'Bawang Merah': 90,
    'Bawang Putih': 120,
    'Cabai': 90,
    'Daun Bawang': 60,
    'Kubis': 90
}

In [145]:
data['estimated_time'] = data['label'].map(harvest_time_map)

In [146]:
data.dropna(subset=['estimated_time'], inplace=True)
data['estimated_time'] = data['estimated_time'].astype(int)

In [ ]:
data.to_csv('/home/noturminesv/projects/gis-ml/dataset/crop_recommendation_range_with_estimated_time.csv', index=False)